// const sing = async () => {
//   throw new Error("I am a bad singer!");
//   return "LA LA LA LA";
// };

// // The function is declared as async, so it returns a promise
// sing()
//   .then((data) => {
//     console.log("Promise resolved with: ", data);
//   })
//   .catch((err) => {
//     console.log("Promise rejected with: ", err.message);
//   });

